services:
  - type: web
    name: deckworthy
    env: node
    plan: free
    buildCommand: npm install && npm run init-db
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STEAM_API_KEY
        sync: false
      - key: ITAD_API_KEY
        sync: false
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/deckworthy.db
    healthCheckPath: /health
    autoDeploy: true
