apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-protondb
  namespace: deckworthy
  labels:
    app: deckworthy
    job: sync-protondb
spec:
  # Daily at 2am (configurable)
  schedule: "0 2 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 3600  # 1 hour timeout
      template:
        metadata:
          labels:
            app: deckworthy
            job: sync-protondb
        spec:
          restartPolicy: OnFailure

          securityContext:
            fsGroup: 1001
            runAsUser: 1001
            runAsNonRoot: true

          containers:
          - name: sync-protondb
            image: deckworthy:latest
            imagePullPolicy: IfNotPresent
            command: ["node", "dist/jobs/sync-protondb.js"]

            envFrom:
            - configMapRef:
                name: deckworthy-config
            - secretRef:
                name: deckworthy-secrets

            volumeMounts:
            - name: data
              mountPath: /app/data

            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: deckworthy-data
