apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deckworthy

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  # - secret.yaml  # Uncomment after creating from secret.yaml.example
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob-sync-games.yaml
  - cronjob-sync-protondb.yaml
  - cronjob-sync-prices.yaml

labels:
  - pairs:
      app: deckworthy
