apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deckworthy-dev

bases:
  - ../../base

nameSuffix: -dev

labels:
  - pairs:
      environment: dev

patches:
  # Reduce resource requests for dev environment
  - target:
      kind: Deployment
      name: deckworthy
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Update namespace metadata
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: deckworthy-dev
      - op: replace
        path: /metadata/labels/environment
        value: dev
